tasks/urls.py
from django.urls import path

from .views import (
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    task_change_status, TaskListView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
        "tasks/<int:pk>/taskchangestatus/",
        task_change_status,
        name="task-change-status",
    ),
]

app_name = "tasks"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models
from django.utils.functional import cached_property


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag', related_name='tasks')

    @cached_property
    def tags_to_str(self):
        return ", ".join(self.tags.all().values_list('name', flat=True))

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

tasks/forms.py
from datetime import datetime

from django import forms

from .models import Task


class DateTimeWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        date_attrs = {'type': 'date'}
        time_attrs = {'type': 'time'}
        if attrs:
            date_attrs.update(attrs)
            time_attrs.update(attrs)

        widgets = (forms.DateInput(attrs=date_attrs), forms.TimeInput(attrs=time_attrs, format='%H:%M'))
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            return [value.date(), value.time()]
        return [None, None]

    def value_from_datadict(self, data, files, name):
        date_value = self.widgets[0].value_from_datadict(data, files, f'{name}_0')
        time_value = self.widgets[1].value_from_datadict(data, files, f'{name}_1')
        if date_value and time_value:
            full_date_time = f'{date_value} {time_value}'
            return datetime.strptime(full_date_time, '%Y-%m-%d %H:%M')
        return None

    def format_output(self, rendered_widgets):
        return '<div class="datetime-widget">{}</div>'.format(' '.join(rendered_widgets))


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

        widgets = {
            'deadline': DateTimeWidget
        }

tasks/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from .models import Task, Tag
from .forms import TaskForm


class TaskListView(LoginRequiredMixin, generic.ListView):
    template_name = "tasks/index.html"
    context_object_name = "task_list"
    paginate_by = 5

    def get_queryset(self):
        return Task.objects.all().order_by('is_done', '-created_at').prefetch_related('tags')


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "tasks/tag_list.html"
    paginate_by = 5


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")


@login_required
def task_change_status(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("tasks:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}
            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
    <h1>TODO list
        <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page">Add task</a>
    </h1>
    <hr>

    {% for task in task_list %}
        <div>
            <div class="d-flex justify-content-between">
                <h2>
                    {{ task.content }}
                    {% if not task.is_done %}
                        <span class="text-danger">Undone</span>
                    {% else %}
                        <span class="text-success">Done</span>
                    {% endif %}
                </h2>
                <p>
                    {% if task.is_done %}
                        <a class="btn btn-success" href="{% url 'tasks:task-change-status' task.id %}">Complete</a>
                    {% else %}
                        <a class="btn btn-secondary" href="{% url 'tasks:task-change-status' task.id %}">Undo</a>
                    {% endif %}

                </p>
            </div>
            <p>Created: {{ task.created_at }} {% if task.deadline %} <span style="color: #964B00">Deadline: {{ task.deadline }} </span>{% endif %}</p>
            <p class="text-muted">
                Tags: {{ task.tags_to_str }}
                <a href="{% url 'tasks:task-update' task.id %}">Update</a>
                <a href="{% url 'tasks:task-delete' task.id %}">Delete</a>
            </p>
        </div>
        <hr>

    {% empty %}
        <p>No posts available.</p>
    {% endfor %}



{% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ tag }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">No, back</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Back</a>
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      Tags
      <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary link-to-page">
        Add
      </a>
    </h1>

    {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'tasks:tag-update' pk=tag.id %}">Update</a></td>
        <td><a href="{% url 'tasks:tag-delete' pk=tag.id %}">Delete</a></td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no tags.</p>
    {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ task }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">No, back</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Back</a>
  </form>
{% endblock %}